version: "3.1"

services:
  grpc:
    build: .
    container_name: shortlink_grpc
    restart: always
    env_file: ./config/grpc.env
    command: ./app -s database
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: shortlink_db
    restart: always
    env_file: ./config/postgres.env
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d shortlinker -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/var/lib/postgresql/data/

volumes:
  db:
