version: '3'

services:
  elasticsearch:
    image:  cyborgvova/elasticsearch:latest
    container_name: elastic
    restart:  always
    networks:
      - my_network
    ports:
      - 9200:9200
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  server:
    build: .
    container_name: restaurant
    restart:  always
    networks:
      - my_network
    ports:
      - 8888:8888
    command: ./app
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  my_network:
